### ISSUE TITLE
H resets to HH after two-digits

### ISSUE THREAD

**Issue by dsernst** [zippyui/react-time-picker#10]
If I pass in a value of `'0:20'`, the hour picker starts out as just `0`. Good! :+1: 

But then if that field is adjusted to a two digit number, say by pressing the down arrow to roll back to 23, when you press up to go back it appears as `00`. The same thing happens if you go up to `10` and then back down: instead of `9` it will display as `09`.

**Comment by radubrehar** [comment]
We've just deprecated this in favor of https://www.npmjs.com/package/react-date-picker
