### ISSUE TITLE
Can't seem to get the development environment working

### ISSUE THREAD

**Issue by jlebensold** [zippyui/react-time-picker#2]
Hi there,

I'm a bit of a newbie when it comes to NPM, but I'd like to submit a pull request with arrow key support for your component. I tried following the readme, but ended up with a timeout error:

GET http://localhost:9090/webpack-dev-server.js net::ERR_CONNECTION_TIMED_OUT
localhost/:23 GET 
http://localhost:9090/assets/bundle.js net::ERR_CONNECTION_TIMED_OUT

Is there a HOWTO you can point me to for setting up my dev environment? Thanks!

**Comment by radubrehar** [comment]
Hi Jon,

you can send me an email at the email address you can find here: https://github.com/radubrehar and we can share a skype id and I'm happy to have a call at a convenient time and help you get started with npm, webpack and zippyui/react-time-picker.
