### ISSUE TITLE
Typing in time picker

### ISSUE THREAD

**Issue by TimSteenbeke** [zippyui/react-time-picker#23]
You can't type in the time window

Everybody's first reflex is clicking in the time window and starting to type there wanted time.

**Comment by dev-zippyui** [comment]
This component is deprecated. Please use https://www.npmjs.com/package/react-date-picker since it has support for picking time. Thanks.

**Comment by dev-zippyui** [comment]
Please see the component README, which clearly states the deprecation. Thanks!
