### ISSUE TITLE
Safari display: inline-flex issue

### ISSUE THREAD

**Issue by wayferer** [zippyui/react-time-picker#4]
Hi there,

Safari does not support the following:

````
display: inline-flex;
````

it supports it prefixed though:

````
display: -webkit-inline-flex;
````

Is it easy enough to add this in?

Thanks.

**Comment by zippyui-react** [comment]
We've released a new version of the time picker, 1.0.7, you can find it on npm. For examples, head over to http://zippyui.github.io/react-time-picker/ to see the safari bug solved.

Thanks for using the picker. You may be insterested in a data grid for React as well: http://zippyui.github.io/react-datagrid/

**Comment by wayferer** [comment]
Thank you.
