### ISSUE TITLE
Not working for some reason

### ISSUE THREAD

**Issue by yonatanmn** [zippyui/react-time-picker#5]
Installed it, and added to a component - and just not working. 
(tried latest version and @0.1.3)
like this:

````
var MyComp= React.createClass({
  pickTime: function (time) {
        console.log(time)
    }, 
...
  render: function () {
    var VALUE = '14:00:01';
    return (
  ...
   <TimePicker
                value={VALUE}
                onChange={this.pickTime}
   />
...
````

after pressing any arrow, I get in console infinite loop with time progressing
````
14:00:01
13:59:41
13:59:41
13:59:21
13:59:21
13:59:01
etc....
````

Same for:
````
 <TimePicker   defaultValue={'14:00:01'} />
````
display get's crazy

**Comment by zippyui-react** [comment]
The last version is 1.0.8

Are you using that?

**Comment by yonatanmn** [comment]
yes, and tried also 1.0.6 and 0.1.3

**Comment by zippyui-react** [comment]
Here's a short and complete demo for the time picker, I've just tried it and works without any problems

```jsx
'use strict';

var React      = require('react')
var TimePicker = require('react-time-picker')

var VALUE = '17:45'

var App = React.createClass({

    pickTime: function(value) {
        console.log(value)

        //make sure you update the VALUE to be rendered
        VALUE = value

        //refresh the cmp
        this.setState({}) //or this.forceUpdate()
    },

    render: function(){
    	return <TimePicker value={VALUE} onChange={this.pickTime}/>
    }
})

React.render(<App />, document.getElementById('content'))
```
or, the uncontrolled version:
```jsx
'use strict';

var React      = require('react')
var TimePicker = require('react-time-picker')

var App = React.createClass({

    pickTime: function(value) {
        console.log(value)
    },

    render: function(){
    	return <TimePicker defaultValue={'17:45'} onChange={this.pickTime}/>
    }
})

React.render(<App />, document.getElementById('content'))
```

**Comment by yonatanmn** [comment]
Di few more checks - 
It is working, except when I put the Picker in a modal (similar to this - http://jsfiddle.net/LBAr8/)

**Comment by zippyui-react** [comment]
Nice to hear you got it working :)

What problem do you encounter when you put the picker in the modal? Most probably it is related to app logic, and how you create/disponse the modal.

**Comment by yonatanmn** [comment]
I guess so - check the fiddle. 
I started looking at this but don't know the reason. Everything else works in the modal.

**Comment by zippyui-react** [comment]
in the next few days we are releasing a window component for react (which can be modal), and it will play nicely with the time & date pickers, maybe you will be interested in this

**Comment by yonatanmn** [comment]
Already too invested it this.... 
But thanks
