### ISSUE TITLE
Input type support

### ISSUE THREAD

**Issue by wayferer** [zippyui/react-time-picker#7]
It is possible to pass in a prop that sets the input type? This is so that we can control the keyboard that shows on a mobile device

**Comment by zippyui-react** [comment]
Yes, you can use `inputProps`, which controls the props for all inputs, or you can use `hourInputProps` for example, to only control props for the hour input. (see https://github.com/zippyui/react-time-picker/blob/master/src/index.jsx#L445).

Or you can use `inputFactory` (and/or `hourInputFactory`), which, if specified, is called with the built `inputProps`. So it's basically very easy to control the picker input fields.

**Comment by wayferer** [comment]
Thanks for the reply and that does look like what I need but I'm a bit confused on how to use it (sorry). Currently we are using it like this:

````
<ReactTimePicker showArrows={false} hourStep={1} minuteStep={15} timeName='start' value={this.props.start} onChange={this.handleTimeChange} />
````

How would I add `type="tel"` to this?

**Comment by zippyui-react** [comment]
```
<ReactTimePicker showArrows={false} 
inputProps={{type: 'tel'}}
hourStep={1}
minuteStep={15}
timeName='start'
value={this.props.start}
onChange={this.handleTimeChange} />
```

**Comment by wayferer** [comment]
Perfect, thank you.
