### ISSUE TITLE
Provide class names for inner elements (or allow external CSS file)

### ISSUE THREAD

**Issue by Andreyco** [zippyui/react-time-picker#8]
I don't see a problem when JS component depends on CSS. JS and CSS go side by side, Webpack allows loading CSS files, so no problem here.

I see problem on setting styles in JS. This cannot be replaced. External file can be replace. Very easily.

Would you consider putting styling to external CSS, or at least provide class names for inner elements so that can be in easier way?

Thanks.

**Comment by radubrehar** [comment]
Yes, we have no problem with adding css classNames.
Though we offer `minuteInputFactory`, `hourInputFactory`, etc functions to customize rendering anything in the component.

**Comment by radubrehar** [comment]
We've just deprecated this in favor of https://www.npmjs.com/package/react-date-picker
